Added Sarif formatter
mercedes-benz/bandit pull request #1
Opened 2023-10-12 08:54 UTC by alexdd

Sarif interchange format with CWE data is generated using lxml and XSLT.

2023-10-12 10:35 UTC, Jeeppler requested changes
Overall the code looks good, but tests are missing. Please add tests. In addition, I found some issues see comments.

Two controversial features are:

1. the CWE XML file is checked in (the file is huge)
2. the use of lxml which is not part of the standard Python API adds a dependency

We will keep both controversial parts in the code and let the Bandit community decide whether they want to see those parts changed or not.

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif.py
> +This formatter outputs the issues as Sarif.
```suggestion
This formatter outputs the security report in the Static Analysis Results Interchange Format (SARIF)  .
```

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif.py
> +import sys, os, uuid, datetime, json
please write each import into a single line.

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif.py
> +def report(manager, fileobj, sev_level, conf_level, lines=-1):
Is this a function you have to overwrite for bandit or is this "your" function?

In case it is your function please call `sev_level` -> `severity_level`.

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif.py
> +            jsn = json.loads(result.getroot().text)
```suggestion
            json_text  = json.loads(result.getroot().text)
```

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif.py
> +    """Called by the XSLT stylesheet and returns end time utc."""
```suggestion
    """Called by the XSLT stylesheet and returns end time in UTC format."""
```

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif/sarif.xsl
> +     XSLT is used because the Mitre CWE Common Weakness enumeration is also read as an XML file
Please adjust the remaining description.

```suggestion
     XSLT is used because the official MITRE Common Weakness Enumeration (CWE) is available as XML file
```

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif/sarif.xsl
> +     2. Processing Step: The XML structure will be converted to JSON. It will be appended to the root output tree
```suggestion
     2. Processing step: The XML structure will be converted to JSON. It will be appended to the root output tree
```

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif/sarif.xsl
> +                <version json="property">1.7.5</version>
Is there a way to get the version number from Bandit itself. Otherwise the version number will be out of sync for every update.

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif/sarif.xsl
> +            <schema>https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0.json</schema>
The official JSON Schema can be found under a different link: https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json.

Link is mentioned here: https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html

2023-10-12 10:35 UTC, Jeeppler commented on bandit/formatters/sarif/sarif.xsl
> +    <!-- usually you would not need to modify these rules -->
Why do I have to modify these rules? Please clarify the description.

2023-10-13 12:27 UTC, alexdd commented on bandit/formatters/sarif.py
> +def report(manager, fileobj, sev_level, conf_level, lines=-1):
The function signature is common among all formatters. The parameter name `sev_level` appears to be the usual abbreviation in the codebase.

2023-10-13 12:28 UTC, alexdd commented on bandit/formatters/sarif/sarif.xsl
> +                <version json="property">1.7.5</version>
Yes, we can easily get it via `bandit.__version__` and pass it into the XSLT Stylesheet.

2023-10-23 19:52 UTC, Jeeppler approved these changes
Looks good. Let's merge it.

2023-10-24 07:09 UTC, alexdd commented
Hi @Jeeppler,  I don't have write access to the repo, could you please merge it?

2023-11-02 10:35 UTC, Jeeppler commented
We will close this branch as discussed.

2023-11-02 10:35 UTC, closed without merging